server :
  port: 8080


spring:
    application:
        name: gateway-service

    cloud:
        gateway:
            routes:
                - id: fitness-app
                  uri: http://localhost:8081
                  predicates:
                    - Path=/api/fitness-app/**

                - id: auth-service
                  uri: http://localhost:8083
                  predicates:
                    - Path=/api/auth-service/**
            globalcors:
                corsConfigurations:
                    '[/**]':
                        allowedOrigins: "*"
                        allowedMethods:
                            - GET
                            - POST
                            - PUT
                            - DELETE
                            - OPTIONS
                        allowedHeaders: "*"
                        allowCredentials: true

logging:
    file:
        name: logs/gateway-service.log
    level:
        org.springframework.cloud.gateway: DEBUG
        org.springframework.web: DEBUG
        reactor.netty : DEBUG
        root : INFO
        com:
            fitnessapp:
              auth-service: DEBUG
        org:
          hibernate:
            SQL: DEBUG
            type.descriptor.sql.BasicBinder: TRACE
    patterns:
        console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"